// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiXpWDBS__akI-8Ft1nJLa1pncn__c3fY',
    appId: '1:666278182382:web:e329c6c7ace58937fa22ff',
    messagingSenderId: '666278182382',
    projectId: 'qrtec-final-app',
    authDomain: 'qrtec-final-app.firebaseapp.com',
    storageBucket: 'qrtec-final-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCySidz0OoibrNDzdzeNsQxA5p5xdh5fZo',
    appId: '1:666278182382:android:c8597196c934c2a6fa22ff',
    messagingSenderId: '666278182382',
    projectId: 'qrtec-final-app',
    storageBucket: 'qrtec-final-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiuCoM9Mz74ax11DVhMl8QzdXB_QuKsYc',
    appId: '1:666278182382:ios:d6eec77d47bf5a67fa22ff',
    messagingSenderId: '666278182382',
    projectId: 'qrtec-final-app',
    storageBucket: 'qrtec-final-app.firebasestorage.app',
    iosBundleId: 'com.example.qrtecFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiuCoM9Mz74ax11DVhMl8QzdXB_QuKsYc',
    appId: '1:666278182382:ios:d6eec77d47bf5a67fa22ff',
    messagingSenderId: '666278182382',
    projectId: 'qrtec-final-app',
    storageBucket: 'qrtec-final-app.firebasestorage.app',
    iosBundleId: 'com.example.qrtecFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiXpWDBS__akI-8Ft1nJLa1pncn__c3fY',
    appId: '1:666278182382:web:fe320fb8accda062fa22ff',
    messagingSenderId: '666278182382',
    projectId: 'qrtec-final-app',
    authDomain: 'qrtec-final-app.firebaseapp.com',
    storageBucket: 'qrtec-final-app.firebasestorage.app',
  );
}
