// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuqHdb0extEmiICmkchdAP1Zh9UvG2m0I',
    appId: '1:884934582474:web:6d62dd19684994fd549433',
    messagingSenderId: '884934582474',
    projectId: 'qrtec-inventory-app-654f7',
    authDomain: 'qrtec-inventory-app-654f7.firebaseapp.com',
    storageBucket: 'qrtec-inventory-app-654f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Qdbf2WA_cHTlOrOlAh3r_Tii1uTwaG4',
    appId: '1:884934582474:android:14fb410aa686c2f3549433',
    messagingSenderId: '884934582474',
    projectId: 'qrtec-inventory-app-654f7',
    storageBucket: 'qrtec-inventory-app-654f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcOR3_N0RR0W-QTedjXR0E4AJ6v-4Z5b0',
    appId: '1:884934582474:ios:9bfc9c61179dc863549433',
    messagingSenderId: '884934582474',
    projectId: 'qrtec-inventory-app-654f7',
    storageBucket: 'qrtec-inventory-app-654f7.firebasestorage.app',
    iosBundleId: 'com.example.qrtecFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcOR3_N0RR0W-QTedjXR0E4AJ6v-4Z5b0',
    appId: '1:884934582474:ios:9bfc9c61179dc863549433',
    messagingSenderId: '884934582474',
    projectId: 'qrtec-inventory-app-654f7',
    storageBucket: 'qrtec-inventory-app-654f7.firebasestorage.app',
    iosBundleId: 'com.example.qrtecFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuqHdb0extEmiICmkchdAP1Zh9UvG2m0I',
    appId: '1:884934582474:web:d63f22b9ce89f683549433',
    messagingSenderId: '884934582474',
    projectId: 'qrtec-inventory-app-654f7',
    authDomain: 'qrtec-inventory-app-654f7.firebaseapp.com',
    storageBucket: 'qrtec-inventory-app-654f7.firebasestorage.app',
  );

}